matrix_magic/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'determinant/', views.det, name='determinant'),
    url(r'multiply/', views.mult, name='multiply'),
    # url(r'^post/(?P<matrix>\d+)/$', views.calculated, name='calculated')
]

untitled/urls.py
from django.contrib import admin
from django.urls import include, path
from matrix_magic import views

urlpatterns = [
    path('', views.global_index),
    path('admin/', admin.site.urls),
    path('matrix/', include('matrix_magic.urls'))
]

matrix_magic/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class MMatrix(models.Model):
    data = models.TextField()

    def get_data(self):
        return self.data

    def get_matrix(self):
        self.matrix = []
        for row in [r.split(" ") for r in self.data.translate('\r').split('\n')]:
            m_row = []
            for el in row:
                if not(el == '\r'):
                    try:
                        el = float(el)
                        m_row.append(el)
                    except:
                        pass
            self.matrix.append(m_row)

        return self.matrix

    def code_matrix(self):
        self.get_matrix()
        mat_coded = ''
        for row in self.matrix:
            str_row = ''
            for el in row:
                str_row += str(el)+'_'
            mat_coded += str_row+'+'
        print(mat_coded)
        return mat_coded

class MatrixMult():
    pass

matrix_magic/forms.py
from django import forms


class detMatForm(forms.Form):
    data = forms.CharField(widget=forms.Textarea, required=True)


class multMatForm(forms.Form):
    mat_l = forms.CharField(widget=forms.Textarea, required=True)
    mat_r = forms.CharField(widget=forms.Textarea, required=True)

matrix_magic/views.py
from django.shortcuts import render, redirect
from .forms import detMatForm, multMatForm
from .backends import Api


# Create your views here.

def global_index(request):
    return redirect('matrix/')


def index(request):
    return render(request, 'matrix_magic/index.html', {'page_name': 'index'})


def det(request):
    status = 0
    err_code = 200
    msg = None
    ans = None
    if (request.method == 'POST'):
        status = 1
        form = detMatForm(request.POST)
        if form.is_valid():
            post = form.cleaned_data['data']
            err_code, msg, ans = Api.determinant(post)
            # print(err_code, msg, ans)
    else:
        form = detMatForm()

    return render(request, 'matrix_magic/det.html',
                  {'status': status, 'form': form, 'err_code': err_code, 'page_name': 'det',
                   'msg': msg, 'ans': str(ans)})


def mult(request):
    status = 0
    err_code = 200
    msg = None
    ans = None
    if (request.method == 'POST'):
        status = 1
        form = multMatForm(request.POST)
        if form.is_valid():
            mat_l, mat_r = form.cleaned_data['mat_l'], form.cleaned_data['mat_r']
            err_code, msg, ans = Api.multiplication(mat_l, mat_r)
            # print(err_code, msg, type(ans))

    else:
        form = multMatForm()

    return render(request, 'matrix_magic/mult.html',
                  {'status': status, 'form': form, 'err_code': err_code, 'page_name': 'mult',
                   'msg': msg, 'ans': ans})

matrix_magic/templates/matrix_magic/base.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="HomeWork">
    <meta name="author" content="AlexNikolenko">
    <title>Homework #1</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
</head>

<body class="bg-light">

<nav class="navbar navbar-expand-md navbar-light bg-warning">
    <a class="navbar-brand" href="/matrix">Matrix Magic</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if page_name == 'index' %} active {% endif %}">
                <a class="nav-link" href="/matrix">Home</a>
            </li>
            <li class="nav-item {% if page_name == 'det' %} active {% endif %}">
                <a class="nav-link" href="/matrix/determinant/">Determinant</a>
            </li>
            <li class="nav-item {% if page_name == 'mult' %} active {% endif %}">
                <a class="nav-link" href="/matrix/multiply/">Multiply</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container shadow p-3" style="margin-top: 32px; margin-bottom: 64px; background-color: white">

    {% block content %}
    {% endblock %}


</main><!-- /.container -->

<div class="navbar fixed-bottom navbar-light bg-light">

    <div class="container">
        <span class="text-muted align-bottom">By <a href="//t-do.ru/alexnikolenko" target="_blank"
                                                    class="badge badge-secondary align-middle">@alexnikolenko</a> &
            <a href="//t-do.ru/ikkalinkin" target="_blank"
               class="badge badge-secondary align-middle">@ikkalinkin</a></span>
    </div>
    <!--<span class="navbar-text">
              По всем вопросам обращаться <a href="https://telegram.me/alexnikolenko" target="_blank">@alexnikolenko</a>-->

</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

matrix_magic/templates/matrix_magic/det.html
{% extends 'matrix_magic/base.html' %}

{% block content %}

    {% if status == 0 %}


        <h1>
            Вычисление определителя
        </h1>
        <p class="lead">
            На это странице вы можете посчитать определитель матрицы.
        </p>

        <h3>
            Элементы матрицы вводятся через пробел, строчки разделяются пробелом!
        </h3>

        <div id="alerts"></div>

        <form class="form-group" method="post" id="test_form">{% csrf_token %}
            <div class="form-group">
                {{ form.data }}
            </div>
            <div class="form-actions">
                <button type="button" onclick="go();" class="btn btn-warning btn-cm btn-block">Рассчитать</button>
            </div>
            <br>
        </form>

        <script>
            $("#id_data").prop("required", true)
                .addClass("form-control text-monospace")
                .val("1 2 3\n0 2 3\n0 0 3")
                .on({
                    input: function () {
                        refresh_form();
                    }
                });

            function go() {
                if (is_valid($("#id_data").val())) {
                    $('#test_form').submit();
                }
                else {
                    $("#id_data").addClass("is-invalid");
                    Alert('Обязательное поле', 'danger')
                }

            }

            function is_valid(data) {
                return !(data.trim().split(/\s+/)[0] === "")
            }

            function refresh_form() {
                $("#id_data").removeClass("is-invalid");
            }

            function Alert(message, type) {
                $('#alerts').html(
                    '<div class="alert alert-' + type + ' alert-dismissible fade show" role="alert"">' +
                    '<button type="button" class="close" data-dismiss="alert" aria-label="Close" ' +
                    'onclick="refresh_form();">' +
                    '<span aria-hidden="true">&times;</span>' +
                    '</button>' + message + '</div>');
            }
        </script>

    {% elif status == 1 %}
        {% if err_code == 200 %}
            <h2>Полученный определитель равняется: {{ ans }}</h2>

        {% elif err_code == 420 %}

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <a href="/matrix/determinant" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </a>
                {{ msg }}
            </div>
            {#                Что-то пошло не так, свяжитесь с <a class="alert-link"#}
            {#                                                    href="https://telegram.me/alexnikolenko"#}
            {#                                                    target="_blank">@alexnikolenko</a></div>#}
        {% endif %}
        <div class="row">
            <div class="col-xl-6">
                <a href="/matrix/determinant" class="btn btn-warning btn-block" role="button">
                    Хочу еще!
                </a><br>
            </div>

            <div class="col-xl-6">
                <div id="accordion">
                    <button class="btn btn-outline-secondary btn-cm btn-block collapsed" type="button"
                            data-toggle="collapse"
                            data-target="#collapse_0" aria-expanded="false" aria-controls="collapse_0"> Посмотреть
                        алгоритм
                    </button>
                    <div id="collapse_0" class="multi-collapse collapse" style="">
                        <div class="card">
                            {#-------------------------------------------------------#}
                            <!-- HTML generated using hilite.me -->
                            <div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre
                                    style="margin: 0; line-height: 125%"><span
                                    style="color: #008800; font-weight: bold">def</span> <span
                                    style="color: #0066BB; font-weight: bold">det</span>(matrix):
    <span style="color: #DD4422">&#39;&#39;&#39;</span>
<span style="color: #DD4422">    Поиск определителя матрицы, путём приведения её к вверхне треугольному виду методом Гаусса</span>
<span style="color: #DD4422">    :param matrix: Вводимая матрицы</span>
<span style="color: #DD4422">    :return: Определитель</span>
<span style="color: #DD4422">    &#39;&#39;&#39;</span>

    n <span style="color: #333333">=</span> <span style="color: #007020">len</span>(matrix)  <span
                                        style="color: #888888"># Размер матрицы</span>
    ans <span style="color: #333333">=</span> <span style="color: #0000DD; font-weight: bold">1</span>  <span
                                        style="color: #888888"># Начинаем с 1</span>

    <span style="color: #008800; font-weight: bold">for</span> i <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(n <span
                                        style="color: #333333">-</span> <span style="color: #0000DD; font-weight: bold">1</span>):  <span
                                        style="color: #888888"># Пробегаемся по всем столбцам,</span>
        <span style="color: #888888"># ищем каждый раз максимальное оставшееся значение в столбце</span>

        max_i <span style="color: #333333">=</span> i  <span
                                        style="color: #888888"># С какого начали тот и максимальный</span>

        <span style="color: #008800; font-weight: bold">for</span> j <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(i <span
                                        style="color: #333333">+</span> <span style="color: #0000DD; font-weight: bold">1</span>, n):  <span
                                        style="color: #888888"># Ищем в остатках, потому что остальные нули</span>
            <span style="color: #008800; font-weight: bold">if</span> <span style="color: #007020">abs</span>(matrix[j][i]) <span
                                        style="color: #333333">&gt;</span> <span style="color: #007020">abs</span>(matrix[max_i][i]):
                max_i <span style="color: #333333">=</span> j

        <span style="color: #008800; font-weight: bold">if</span> max_i <span style="color: #333333">!=</span> i:  <span
                                        style="color: #888888"># Если это не начальный, то надо поменять местами</span>
            matrix[i], matrix[max_i] <span style="color: #333333">=</span> matrix[max_i], matrix[i]
            ans <span style="color: #333333">*=</span> <span style="color: #333333">-</span><span
                                        style="color: #0000DD; font-weight: bold">1</span>  <span
                                        style="color: #888888"># При смене местами знак определителя меняется</span>

        <span style="color: #008800; font-weight: bold">for</span> j <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(i <span
                                        style="color: #333333">+</span> <span style="color: #0000DD; font-weight: bold">1</span>, n):  <span
                                        style="color: #888888"># &quot;Убиваем&quot; элементы под максимальным</span>

            <span style="color: #888888"># Если в какой-то момент разделили на нуль,</span>
            <span style="color: #888888"># это означает, что матрица вырождена</span>
            <span style="color: #008800; font-weight: bold">if</span> matrix[i][i] <span
                                        style="color: #333333">==</span> <span
                                        style="color: #0000DD; font-weight: bold">0</span>:
                <span style="color: #008800; font-weight: bold">return</span> <span
                                        style="color: #6600EE; font-weight: bold">0.0</span>

            <span style="color: #888888"># На диагонали не нулевой, продолжаем &quot;убивать&quot; строки</span>
            t <span style="color: #333333">=</span> matrix[j][i] <span style="color: #333333">/</span> matrix[i][i]

            <span style="color: #008800; font-weight: bold">for</span> k <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(i <span
                                        style="color: #333333">+</span> <span style="color: #0000DD; font-weight: bold">1</span>, n):  <span
                                        style="color: #888888"># Не забываем домножить на коэффциент &quot;убивание&quot; строки</span>
                matrix[j][k] <span style="color: #333333">-=</span> t <span style="color: #333333">*</span> matrix[i][k]

    <span style="color: #008800; font-weight: bold">for</span> i <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(n <span
                                        style="color: #333333">-</span> <span style="color: #0000DD; font-weight: bold">1</span>, <span
                                        style="color: #333333">-</span><span
                                        style="color: #0000DD; font-weight: bold">1</span>, <span
                                        style="color: #333333">-</span><span
                                        style="color: #0000DD; font-weight: bold">1</span>):  <span
                                        style="color: #888888"># Перемножаем диагональ</span>
        ans <span style="color: #333333">*=</span> matrix[i, i]
    <span style="color: #888888"># fixes for fancy looking. (с) Костыли&amp;Велосипеды prod.</span>
    <span style="color: #008800; font-weight: bold">return</span> <span
                                        style="color: #6600EE; font-weight: bold">0.0</span> <span
                                        style="color: #008800; font-weight: bold">if</span> ans <span
                                        style="color: #333333">==</span> <span
                                        style="color: #6600EE; font-weight: bold">0.0</span> <span
                                        style="color: #008800; font-weight: bold">else</span> ans
</pre>
                            </div>

                            {#-------------------------------------------------------#}
                        </div>
                    </div>
                    <br></div>
            </div>
        </div>

    {% endif %}


{% endblock %}

matrix_magic/templates/matrix_magic/mult.html
{% extends 'matrix_magic/base.html' %}

{% block content %}

    {% if status == 0 %}
        <h1>
            Вычисление произведения матрицы
        </h1>
        <p class="lead">
            На это странице вы можете посчитать произведение двух матриц.
        </p>

        <h3>
            Элементы матрицы вводятся через пробел, строчки разделяются пробелом!
        </h3>

        <div id="alerts"></div>

        <form class="form-group" method="post" id="test_form">{% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="lg-4 col-lg-6">
                        <label for="id_mat_l" style="margin-top: 16px;">Левая матрица</label>
                        {{ form.mat_l }}
                    </div>
                    <div class="lg-4 col-lg-6">
                        <label for="id_mat_r" style="margin-top: 16px;">Правая матрица</label>
                        {{ form.mat_r }}
                    </div>
                </div>
            </div>
            <div class="form-actions">
                <button type="button" onclick="go();" class="btn btn-warning btn-cm btn-block">Рассчитать</button>
            </div>
            <br>
        </form>

        <script>
            var id_mat_l = $('#id_mat_l');
            var id_mat_r = $('#id_mat_r');

            id_mat_l
                .prop("required", true)
                .addClass("form-control text-monospace")
                .val("1 2 3\n0 2 3\n0 0 3")
                .on({
                    input: function () {
                        id_mat_l.removeClass("is-invalid")
                    }
                });

            id_mat_r
                .prop("required", true)
                .addClass("form-control text-monospace")
                .val("1 2 3\n0 2 3\n0 0 3")
                .on({
                    input: function () {
                        id_mat_r.removeClass("is-invalid")
                    }
                });

            function go() {
                if (is_valid(id_mat_l.val()) && is_valid(id_mat_r.val())) {
                    $('#test_form').submit();
                }
                if (!is_valid(id_mat_l.val())) {
                    id_mat_l.addClass("is-invalid");
                    Alert('Обязательное поле', 'danger')
                }
                if (!is_valid(id_mat_r.val())) {
                    id_mat_l.addClass("is-invalid");
                    Alert('Обязательное поле', 'danger')
                }

            }

            function is_valid(data) {
                return !(data.trim().split(/\s+/)[0] === "")
            }

            function refresh_form() {
                id_mat_r
                    .removeClass("is-invalid");
                id_mat_l
                    .removeClass("is-invalid");
            }

            function Alert(message, type) {
                $('#alerts').html(
                    '<div class="alert alert-' + type + ' alert-dismissible fade show" role="alert"">' +
                    '<button type="button" class="close" data-dismiss="alert" aria-label="Close" ' +
                    'onclick="refresh_form();">' +
                    '<span aria-hidden="true">&times;</span>' +
                    '</button>' + message + '</div>');
            }
        </script>

    {% elif status == 1 %}
        {% if err_code == 200 %}
            <h2>Результирующая матрица:</h2>

            <div class="card shadow-lg border-warning" style="margin-bottom: 32px; margin-top: 16px;">
                <div class="card-body">
                    <div class="text-monospace align-items-center text-justify text-center">
                        <pre style="margin-bottom: -8px; margin-top: -8px;">{{ ans }}</pre>
                    </div>
                </div>
            </div>

        {% elif err_code == 420 %}

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                <a href="/matrix/multiply" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </a>
                {{ msg }}
            </div>
            {#                Что-то пошло не так, свяжитесь с <a class="alert-link"#}
            {#                                                    href="https://telegram.me/alexnikolenko"#}
            {#                                                    target="_blank">@alexnikolenko</a></div>#}
        {% endif %}
        <div class="row">
            <div class="col-xl-6">
                <a href="/matrix/multiply" class="btn btn-warning btn-block" role="button">
                    Хочу еще!
                </a><br>
            </div>

            <div class="col-xl-6">
                <div id="accordion">
                    <button class="btn btn-outline-secondary btn-cm btn-block collapsed" type="button"
                            data-toggle="collapse"
                            data-target="#collapse_0" aria-expanded="false" aria-controls="collapse_0"> Посмотреть
                        алгоритм
                    </button>
                    <div id="collapse_0" class="multi-collapse collapse" style="">
                        <div class="card">
                            {#-------------------------------------------------------#}
                            <!-- HTML generated using hilite.me -->
                            <div style="background: #ffffff; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;"><pre
                                    style="margin: 0; line-height: 125%"><span
                                    style="color: #008800; font-weight: bold">def</span> <span
                                    style="color: #0066BB; font-weight: bold">mul</span>(l, r):
    <span style="color: #DD4422">&#39;&#39;&#39;</span>
<span style="color: #DD4422">    Произведение двух матриц &quot;влоб&quot;. Для этого был написан специальный класс Matrix с методом .shape</span>
<span style="color: #DD4422">    :param l: Левая матрица</span>
<span style="color: #DD4422">    :param r: Правая матрица</span>
<span style="color: #DD4422">    :return: класс Матрицы, полученной произведением</span>
<span style="color: #DD4422">    &#39;&#39;&#39;</span>
    <span style="color: #008800; font-weight: bold">if</span> l<span style="color: #333333">.</span>shape[<span
                                        style="color: #0000DD; font-weight: bold">1</span>] <span
                                        style="color: #333333">!=</span> r<span
                                        style="color: #333333">.</span>shape[<span
                                        style="color: #0000DD; font-weight: bold">0</span>]:
        <span style="color: #008800; font-weight: bold">raise</span> NotConsistedMatrices <span style="color: #888888"># Матрицы не согласованны</span>

    n, m, p <span style="color: #333333">=</span> l<span style="color: #333333">.</span>shape[<span
                                        style="color: #0000DD; font-weight: bold">0</span>], r<span
                                        style="color: #333333">.</span>shape[<span
                                        style="color: #0000DD; font-weight: bold">1</span>], l<span
                                        style="color: #333333">.</span>shape[<span
                                        style="color: #0000DD; font-weight: bold">1</span>] <span
                                        style="color: #888888"># Запоминаем размеры матриц.</span>
    <span style="color: #888888"># Метод .shape -- возвращает (N, M) если матрица размером NxM</span>
    lst <span style="color: #333333">=</span> [] <span style="color: #888888"># Итоговая матрица произведения</span>

    <span style="color: #008800; font-weight: bold">for</span> i <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(n): <span style="color: #888888"># Пробегаем все строчки</span>
        lst<span style="color: #333333">.</span>append([])
        <span style="color: #008800; font-weight: bold">for</span> j <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(m):
            prod <span style="color: #333333">=</span> <span style="color: #0000DD; font-weight: bold">0</span> <span
                                        style="color: #888888"># Элемент текущей суммы</span>
            <span style="color: #008800; font-weight: bold">for</span> k <span
                                        style="color: #000000; font-weight: bold">in</span> <span
                                        style="color: #007020">range</span>(p):
                prod <span style="color: #333333">+=</span> l[i, k] <span style="color: #333333">*</span> r[k, j]
            lst[i]<span style="color: #333333">.</span>append(prod)

    <span style="color: #008800; font-weight: bold">return</span> Matrix(lst) <span style="color: #888888"># Возвращает класс Матрицы</span>
</pre>
                            </div>

                            {#-------------------------------------------------------#}
                        </div>
                    </div>
                    <br></div>
            </div>
        </div>

    {% endif %}


{% endblock %}